### ISSUE TITLE
import 9hits

### ISSUE THREAD

**Issue by MadHunter141** [OwElko/9hits-External-Proxies-API#1]
Hello. Tell me how to import a file from ssh? what format should it have? ssh|IP xxx.xxx.xxx.xxx|login|password or other format?

**Comment by OwElko** [comment]
The accepted format includes the following information: type -> address:port -> user -> password. The information must be in exactly the order, can be separated by one of the characters ;, |, space. address is required, the rest is optional. If type is not specified, the default type you choose will be used.

11.11.11.11:8080
22.22.22.22:88;admin;123456
33.33.33.33|admin|123456
44.44.44.44     admin     123456
http;55.55.55.55:88
http;66.66.66.66:8080;user;password
ssh;77.77.77.77;user;password
ssh|88.88.88.88|user|password
socks4|88.88.88.88:9999
socks5      99.99.99.99

**Comment by ScripticusKodius** [comment]
there is an SQL base containing the right format on how to add proxies 
https://github.com/OwElko/9hits-External-Proxies-API/blob/master/proxies.sql
